### PR TITLE
Fixed typo (payload was misspelled as paylod)

### PR DESCRIPTION
**Pull request by wjgilmore**

### CODE REVIEW

**Comment by parkr** [comment]
:shipit:

**Comment by imathis** [comment]
Good catch. Thanks!

**Comment by wjgilmore** [comment]
I do what I can lol. Love Octopress. Use it to run both http://www.easyactiverecord.com and http://www.easylaravelbook.com/, it works flawlessly.

**Comment by imathis** [comment]
Nice!

**Pull request merged**
